import { Student } from './student';

export const STUDENTS: Student[] = [
    {id: 1,
    name: "Lucious Malfoy",
    year: 4,
    house: "Slytherin",
    score: 150,},
    {id: 2,
    name: "Cedric Diggory",
    year: 2,
    house: "Hufflepuff",
    score: 100,},
    {id: 3,
    name: "Luna Lovegood",
    year: 1,
    house: "Ravenclaw",
    score: 225,},
    {id: 4,
    name: "James Potter",
    year: 4,
    house: "Gryffindor",
    score: 70,},

    {id: 5,
    name: "Severus Snape",
    year: 4,
    house: "Slytherin",
    score: 150,},
    {id: 6,
    name: "Newton Scamander",
    year: 3,
    house: "Hufflepuff",
    score: 200,},
    {id: 7,
    name: "Cho Chang",
    year: 1,
    house: "Ravenclaw",
    score: 90,},
    {id: 8,
    name: "Remus Lupin",
    year: 4,
    house: "Gryffindor",
    score: 120,},

    {id: 9,
    name: "Leta Lestrange",
    year: 3,
    house: "Slytherin",
    score: 95,},
    {id: 10,
    name: "Nymphadora Tonks",
    year: 3,
    house: "Hufflepuff",
    score: 175,},
    {id: 11,
    name: "Myrtle Warren",
    year: 2,
    house: "Ravenclaw",
    score: 125,},
    {id: 12,
    name: "Ginevra Weasley",
    year: 1,
    house: "Gryffindor",
    score: 115,},

    {id: 13,
    name: "Marcus Flint",
    year: 2,
    house: "Slytherin",
    score: 35,},
    {id: 14,
    name: "Theseus Scamander",
    year: 4,
    house: "Hufflepuff",
    score: 25,},
    {id: 15,
    name: "Gilderoy Lockhart",
    year: 4,
    house: "Ravenclaw",
    score: 10,},
    {id: 16,
    name: "Ron Weasley",
    year: 1,
    house: "Gryffindor",
    score: 150,}, 
];